# Generated by Django 3.1.2 on 2020-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('surname', models.CharField(max_length=300, verbose_name='Surname')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
    ]
