# Generated by Django 3.1.1 on 2021-01-05 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30, verbose_name='Type')),
                ('name', models.CharField(max_length=22, verbose_name='Name')),
                ('model', models.CharField(max_length=25, verbose_name='Model')),
                ('color', models.CharField(max_length=22, verbose_name='Color')),
                ('condition', models.CharField(max_length=22, verbose_name='Condition')),
                ('description', models.TextField(max_length=1523, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Description')),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=33, verbose_name='Place')),
                ('photo', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
