# Generated by Django 3.1.2 on 2020-11-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('headphones', 'Headphones'), ('monitor', 'Monitor'), ('component', 'Component'), ('ga', 'Gaming Accessories')], max_length=100, verbose_name='Type')),
                ('model', models.CharField(max_length=200, verbose_name='Model')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('color', models.CharField(choices=[('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('gold', 'Gold'), ('red', 'Red'), ('silver', 'Silver'), ('pink', 'Pink'), ('gray', 'Gray'), ('blue', 'Blue'), ('purple', 'Purple'), ('black', 'Black'), ('other', 'Other')], max_length=100, verbose_name='Color')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=100, verbose_name='Condition')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=155, verbose_name='Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=255, upload_to='', verbose_name='URL')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ad')),
            ],
        ),
    ]
