# Generated by Django 3.1.1 on 2021-01-03 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201229_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(max_length=22, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(max_length=22, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=1523, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(max_length=22, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=22, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='place',
            field=models.CharField(max_length=37, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='AdPhoto',
        ),
    ]
