# Generated by Django 3.1.1 on 2021-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210103_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(upload_to='polls/static/img/'),
        ),
    ]
