# Generated by Django 3.1.1 on 2021-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210103_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.FileField(upload_to='ProjectforIntership\\polls\\static\\polls\\img'),
        ),
    ]
