# Generated by Django 3.1.1 on 2021-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210103_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='place',
            field=models.CharField(max_length=22, verbose_name='Place'),
        ),
    ]
