# Generated by Django 3.1.1 on 2021-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210104_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(max_length=25, verbose_name='Model'),
        ),
    ]
