# Generated by Django 3.1.1 on 2021-01-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210104_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='place',
            field=models.CharField(max_length=30, verbose_name='Place'),
        ),
    ]
